
  CREATE TABLE "HORARIOS_MEZANINO" 
   (	"ID_HORARIO" NUMBER, 
	"ID_RESERVA" NUMBER NOT NULL ENABLE, 
	"DAT" DATE NOT NULL ENABLE, 
	"HOR_INICIO" VARCHAR2(200) NOT NULL ENABLE, 
	"HOR_FIM" VARCHAR2(200) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID_HORARIO")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "HORARIOS_MEZANINO" ADD CONSTRAINT "ID_RESERVA" FOREIGN KEY ("ID_RESERVA")
	  REFERENCES "RESERVAS" ("ID_RESERVA") ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_HORARIOS_MEZANINO_B_I" 
BEFORE INSERT ON HORARIOS_MEZANINO  
FOR EACH ROW  
BEGIN  
    -- Gerar ID automaticamente (ok, não causa mutação)  
    SELECT SEQ_HORARIOS_MEZANINO.NEXTVAL INTO :NEW.ID_HORARIO FROM DUAL;  
END;  
 